baseURL = 'https://ponix.dev/'
languageCode = 'en-us'
title = 'Ponix'
theme = 'PaperMod'

[params]
author = 'Simon Rall'
defaultTheme = 'auto'
ShowReadingTime = true
ShowBreadCrumbs = true
ShowPostNavLinks = true

[params.homeInfoParams]
Title = "Aquaponics and Software Blog"
Content = "ğŸŸğŸŒ±ğŸ’»"

[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 2
