baseURL = 'https://ponix.dev/'
languageCode = 'en-us'
title = 'Ponix'
theme = 'PaperMod'

[params]
author = 'Simon Rall'
defaultTheme = 'auto'
ShowReadingTime = true
ShowBreadCrumbs = true
ShowPostNavLinks = true

[params.homeInfoParams]
Title = "ğŸŸğŸŒ±ğŸ’»"
Content = "Hi, I'm Simon Rall. I write software for a living. In my free time, I do a lot of gardening and playing with aquaponics. I am hoping to find where those two worlds meet."

[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 2
